pipeline:
  install:
    image: node:18
    commands:
      - yarn
  lint:
    image: node:18
    commands:
      - yarn lint
  build:
    image: node:18
    commands:
      - yarn build:cloudflare
  publish:
    image: cofob/wrangler
    commands:
      - wrangler pages publish --project-name=firesquare --branch=${CI_COMMIT_SOURCE_BRANCH} --commit-dirty=true .svelte-kit/cloudflare
    secrets: [CF_API_TOKEN, CF_ACCOUNT_ID]
