pipeline:
  install:
    image: node:18
    commands:
      - yarn
  lint:
    image: node:18
    commands:
      - yarn lint
  build-static:
    image: node:18
    commands:
      - yarn build:static
  publish-static:
    image: cofob/ipfs-cluster-ctl
    commands:
      - ipfs-cluster-ctl --host /dns4/rat.frsqr.xyz/tcp/9094 --basic-auth default:$CLUSTER_SECRET add -r --expire-in 2160h --name frontend/preview/$(date +%s) -Q build/ > cid.txt
      - cat cid.txt
      - echo "https://ipfsqr.ru/ipfs/$(cat cid.txt)"
    secrets: [CLUSTER_SECRET]
  build-cloudflare:
    image: node:18
    commands:
      - yarn build:cloudflare
  publish-cloudflare:
    image: cofob/wrangler
    commands:
      - wrangler pages publish --project-name=firesquare --branch=${CI_COMMIT_SOURCE_BRANCH} --commit-dirty=true .svelte-kit/cloudflare
    secrets: [CF_API_TOKEN, CF_ACCOUNT_ID]
